/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import entidades.Componente;
import entidades.Produto;
import entidades.ProdutoManufaturado;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.IComponenteDao;
import persistencia.IProdutoDao;
import persistenciaSql.ComponenteDao;
import persistenciaSql.ProdutoDao;

public class Componentes extends javax.swing.JFrame {


    public Componentes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jpanel_Componentes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_produtoId = new javax.swing.JTextField();
        jLabel_nomeProduto = new javax.swing.JLabel();
        txt_nomeProduto = new javax.swing.JTextField();
        button_buscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_qtdComponente = new javax.swing.JTextField();
        button_adicionar = new javax.swing.JButton();
        button_ListarTodosComp = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_componentes = new javax.swing.JTable();
        button_excluir = new javax.swing.JButton();
        jComboBox_descricaoComponente = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Componentes");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        Jpanel_Componentes.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Produto Id");

        jLabel_nomeProduto.setText("Nome");

        button_buscar.setText("Buscar");
        button_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_buscarActionPerformed(evt);
            }
        });

        jLabel2.setText("Componente");

        jLabel3.setText("Quantidade");

        button_adicionar.setText("Adicionar");
        button_adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_adicionarActionPerformed(evt);
            }
        });

        button_ListarTodosComp.setText("Listar Componentes");
        button_ListarTodosComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ListarTodosCompActionPerformed(evt);
            }
        });

        table_componentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto Id", "Componente", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_componentes);

        button_excluir.setText("Excluir");
        button_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_excluirActionPerformed(evt);
            }
        });

        jComboBox_descricaoComponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_descricaoComponenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Jpanel_ComponentesLayout = new javax.swing.GroupLayout(Jpanel_Componentes);
        Jpanel_Componentes.setLayout(Jpanel_ComponentesLayout);
        Jpanel_ComponentesLayout.setHorizontalGroup(
            Jpanel_ComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_ComponentesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Jpanel_ComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Jpanel_ComponentesLayout.createSequentialGroup()
                        .addGroup(Jpanel_ComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Jpanel_ComponentesLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txt_qtdComponente, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(button_ListarTodosComp))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel_ComponentesLayout.createSequentialGroup()
                        .addGroup(Jpanel_ComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Jpanel_ComponentesLayout.createSequentialGroup()
                                .addGroup(Jpanel_ComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(Jpanel_ComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(Jpanel_ComponentesLayout.createSequentialGroup()
                                        .addComponent(jComboBox_descricaoComponente, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(127, 127, 127)
                                        .addComponent(button_adicionar))
                                    .addGroup(Jpanel_ComponentesLayout.createSequentialGroup()
                                        .addComponent(txt_produtoId, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel_nomeProduto)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_nomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(Jpanel_ComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(button_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(button_buscar))))
                        .addGap(29, 29, 29))))
        );
        Jpanel_ComponentesLayout.setVerticalGroup(
            Jpanel_ComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_ComponentesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(Jpanel_ComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_produtoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_nomeProduto)
                    .addComponent(txt_nomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_buscar))
                .addGap(62, 62, 62)
                .addGroup(Jpanel_ComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(button_adicionar)
                    .addComponent(button_excluir)
                    .addComponent(jComboBox_descricaoComponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Jpanel_ComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_qtdComponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(button_ListarTodosComp)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Jpanel_Componentes);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_buscarActionPerformed
        try {
            List<Produto> produtosInsumos = null; 
            Produto produto; 
            IProdutoDao iProdutoDao = new ProdutoDao(); 
            produto = iProdutoDao.getProdutoId(Integer.parseInt(txt_produtoId.getText())); 
            jComboBox_descricaoComponente.removeAllItems(); // Limpa o JComboBox
            if(produto instanceof ProdutoManufaturado){
                txt_nomeProduto.setText(produto.getNome());
                produtosInsumos = iProdutoDao.getProdutosTipo("PI");  // Retorna todos os Insumos do Banco de Dados
                jComboBox_descricaoComponente.addItem("");
                for(int iCont= 0; iCont < produtosInsumos.size(); iCont++ ){
                    produto = produtosInsumos.get(iCont); 
                    jComboBox_descricaoComponente.addItem(produto.getNome()); //
                }
            }
                
            else
                JOptionPane.showMessageDialog(null, "Não é permitido cadastrar componente para Insumo");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possível encotrar o produto");
        }
    }//GEN-LAST:event_button_buscarActionPerformed

    private void button_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_adicionarActionPerformed
        try {
            Produto produto;
            IProdutoDao iProdutoDao = new ProdutoDao();
            IComponenteDao iComponenteDao = new ComponenteDao();
            Componente componente; 
            String nomeComponente; 
            int id = Integer.parseInt(txt_produtoId.getText()); 
            produto = iProdutoDao.getProdutoId(id);
            if(produto instanceof ProdutoManufaturado){
                nomeComponente =  (String) jComboBox_descricaoComponente.getSelectedItem(); 
                if(!nomeComponente.equals("")){
                    componente = new Componente(nomeComponente, Float.parseFloat(txt_qtdComponente.getText()));
                    componente.setProdutoId(id);
                    iComponenteDao.salvarComponente(componente);
                    txt_qtdComponente.setText("");
                    jComboBox_descricaoComponente.setSelectedIndex(0); // Retornar para a linha sem Item. 
                }
                else{
                    JOptionPane.showMessageDialog(null, "Informar o Componente");
                }
                
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_button_adicionarActionPerformed

    private void button_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_excluirActionPerformed
        IComponenteDao iComponente =  new ComponenteDao(); 
        Componente componente; 
        String nomeComponente = (String) jComboBox_descricaoComponente.getSelectedItem();
        if(!txt_produtoId.getText().isEmpty() && !nomeComponente.equals("")){
            try {
                componente = new Componente(nomeComponente, 0);
                componente.setProdutoId(Integer.parseInt(txt_produtoId.getText()));
                iComponente.deleteComponete(componente);
                jComboBox_descricaoComponente.setSelectedIndex(0);
                txt_qtdComponente.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao excluir o Componente");
            }
       }
    }//GEN-LAST:event_button_excluirActionPerformed
 
    private void button_ListarTodosCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ListarTodosCompActionPerformed
        IComponenteDao iComponenteDao = new ComponenteDao(); 
        List<Componente> componentes = new ArrayList(); 
        Componente componente; 
        DefaultTableModel auxTabela = (DefaultTableModel) table_componentes.getModel(); 
        auxTabela.setNumRows(0);
        if(!txt_produtoId.getText().isEmpty()){
            try {
                componentes = iComponenteDao.getComponentes(Integer.parseInt(txt_produtoId.getText()));
                for (int iCont = 0; iCont < componentes.size(); iCont++) {
                    componente = componentes.get(iCont);
                    Object[] dados = {componente.getProdutoId(), componente.getDescricao(), componente.getQtd()};
                    auxTabela.addRow(dados);
                }
            } catch (Exception ex) {
                Logger.getLogger(Componentes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Informar o id do produto");
        }
    }//GEN-LAST:event_button_ListarTodosCompActionPerformed

    private void jComboBox_descricaoComponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_descricaoComponenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_descricaoComponenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Componentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Componentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Componentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Componentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Componentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jpanel_Componentes;
    private javax.swing.JButton button_ListarTodosComp;
    private javax.swing.JButton button_adicionar;
    private javax.swing.JButton button_buscar;
    private javax.swing.JButton button_excluir;
    private javax.swing.JComboBox<String> jComboBox_descricaoComponente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_nomeProduto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_componentes;
    private javax.swing.JTextField txt_nomeProduto;
    private javax.swing.JTextField txt_produtoId;
    private javax.swing.JTextField txt_qtdComponente;
    // End of variables declaration//GEN-END:variables
}
