/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controler.ControlerViewProdutos;
//import entidades.Estoque;
//import entidades.Insumo;
//import entidades.Produto;
//import entidades.ProdutoManufaturado;
//import java.util.ArrayList;
//import java.util.List;
//import java.util.logging.Level;
//import java.util.logging.Logger;
//import javax.swing.JOptionPane;
//import javax.swing.table.DefaultTableModel;
//import persistencia.IFornecedorDao;
//import persistencia.IProdutoDao;
//import persistenciaSql.FornecedorDao;
//import persistenciaSql.ProdutoDao;

/**
 *
 * @author Rodrigo
 */
public class Produtos extends javax.swing.JFrame {

    /**
     * Creates new form AtualizarProdutos
     */
    private ControlerViewProdutos controler;

    public Produtos() {
        initComponents();
        // opProdutos("SALVAR");
    }

//    public void loadTable(List<Produto> produtos){
//    }
    public void setControlerViewProdutos(ControlerViewProdutos controler) {
        this.controler = controler;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txt_valorAtual = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        radioButton_insumo = new javax.swing.JRadioButton();
        radioButton_PManufaturado = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txt_nomeFornecedor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        radioButton_opEstoqueSim = new javax.swing.JRadioButton();
        radioButton_opEstoqueNao = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        txt_valorMinimo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_nomeProduto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_formulaQuimica = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_grauToxico = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_valorMaximo = new javax.swing.JTextField();
        button_buscarTodos = new javax.swing.JButton();
        button_buscarProdutoID = new javax.swing.JButton();
        txt_produto_id_aux = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_fornecedor_id = new javax.swing.JTextField();
        button_verificarFornecedor = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        button_salvar = new javax.swing.JButton();
        button_atualizar = new javax.swing.JButton();
        button_cancelar = new javax.swing.JButton();
        button_excluir = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txt_produtoId = new javax.swing.JTextField();
        button_alterarTipo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produtos");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel10.setText("Valor Atual");

        jLabel5.setText("Tipo");

        buttonGroup1.add(radioButton_insumo);
        radioButton_insumo.setText("Insumo");
        radioButton_insumo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioButton_insumoMouseClicked(evt);
            }
        });
        radioButton_insumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton_insumoActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioButton_PManufaturado);
        radioButton_PManufaturado.setText("Produto Maufaturado");
        radioButton_PManufaturado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioButton_PManufaturadoMouseClicked(evt);
            }
        });
        radioButton_PManufaturado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton_PManufaturadoActionPerformed(evt);
            }
        });

        jLabel6.setText("Fornecedor");

        jLabel7.setText("Cadastrar Estoque");

        buttonGroup2.add(radioButton_opEstoqueSim);
        radioButton_opEstoqueSim.setText("Sim");
        radioButton_opEstoqueSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton_opEstoqueSimActionPerformed(evt);
            }
        });

        buttonGroup2.add(radioButton_opEstoqueNao);
        radioButton_opEstoqueNao.setText("Nao");
        radioButton_opEstoqueNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton_opEstoqueNaoActionPerformed(evt);
            }
        });

        jLabel8.setText("Valor Minimo");

        jLabel2.setText("Nome");

        txt_nomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomeProdutoActionPerformed(evt);
            }
        });

        jLabel1.setText("Formula Quimica");

        jLabel4.setText("Grau Toxico");

        txt_grauToxico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_grauToxicoActionPerformed(evt);
            }
        });

        jLabel9.setText("Valor Maximo");

        button_buscarTodos.setText("Buscar Todos");
        button_buscarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_buscarTodosActionPerformed(evt);
            }
        });

        button_buscarProdutoID.setText("Buscar Produto ID");
        button_buscarProdutoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_buscarProdutoIDActionPerformed(evt);
            }
        });

        txt_produto_id_aux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_produto_id_auxActionPerformed(evt);
            }
        });

        jLabel3.setText("Id");
        jLabel3.setMaximumSize(new java.awt.Dimension(11, 20));
        jLabel3.setMinimumSize(new java.awt.Dimension(11, 20));
        jLabel3.setPreferredSize(new java.awt.Dimension(11, 20));

        txt_fornecedor_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fornecedor_idActionPerformed(evt);
            }
        });

        button_verificarFornecedor.setText("Verificar");
        button_verificarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_verificarFornecedorActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Formula Quimica", "Tipo", "Fornecedor", "Valor Minimo", "Valor Maximo", "valor Atual"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setPreferredWidth(30);
            tabela.getColumnModel().getColumn(1).setPreferredWidth(70);
            tabela.getColumnModel().getColumn(3).setPreferredWidth(15);
            tabela.getColumnModel().getColumn(5).setPreferredWidth(18);
            tabela.getColumnModel().getColumn(6).setPreferredWidth(18);
            tabela.getColumnModel().getColumn(7).setPreferredWidth(18);
        }

        button_salvar.setText("Salvar");
        button_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_salvarActionPerformed(evt);
            }
        });

        button_atualizar.setText("Atualizar");
        button_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_atualizarActionPerformed(evt);
            }
        });

        button_cancelar.setText("Cancelar");
        button_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelarActionPerformed(evt);
            }
        });

        button_excluir.setText("Excluir");
        button_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_excluirActionPerformed(evt);
            }
        });

        jLabel11.setText("ID");

        txt_produtoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_produtoIdActionPerformed(evt);
            }
        });

        button_alterarTipo.setText("Desbloquear Tipo");
        button_alterarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_alterarTipoActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar Pelo Nome");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_buscarTodos)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(button_buscarProdutoID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_produto_id_aux, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(35, 35, 35)
                                .addComponent(radioButton_opEstoqueSim)
                                .addGap(45, 45, 45)
                                .addComponent(radioButton_opEstoqueNao))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(radioButton_PManufaturado)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(18, 18, 18)
                                            .addComponent(txt_valorMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(38, 38, 38)
                                            .addComponent(jLabel9)
                                            .addGap(31, 31, 31)
                                            .addComponent(txt_valorMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(51, 51, 51)
                                        .addComponent(txt_valorAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(txt_fornecedor_id, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(109, 109, 109)
                                .addComponent(button_verificarFornecedor))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(radioButton_insumo)
                                            .addComponent(txt_nomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_produtoId, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt_grauToxico, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(48, 48, 48)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel1))))))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_formulaQuimica, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(button_alterarTipo))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_salvar)
                .addGap(28, 28, 28)
                .addComponent(button_atualizar)
                .addGap(29, 29, 29)
                .addComponent(button_excluir)
                .addGap(29, 29, 29)
                .addComponent(button_cancelar)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_produtoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_grauToxico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_formulaQuimica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioButton_PManufaturado)
                            .addComponent(radioButton_insumo))
                        .addComponent(button_alterarTipo)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txt_nomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button_verificarFornecedor)
                        .addComponent(txt_fornecedor_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(radioButton_opEstoqueSim)
                    .addComponent(radioButton_opEstoqueNao))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_valorMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txt_valorMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txt_valorAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(button_buscarTodos)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_buscarProdutoID)
                    .addComponent(txt_produto_id_aux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_salvar)
                    .addComponent(button_atualizar)
                    .addComponent(button_cancelar)
                    .addComponent(button_excluir)))
        );

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void radioButton_insumoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioButton_insumoMouseClicked


    }//GEN-LAST:event_radioButton_insumoMouseClicked

    private void radioButton_insumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton_insumoActionPerformed
        controler.opProdutos("LIBERAR_TXT_FORNECEDOR");
    }//GEN-LAST:event_radioButton_insumoActionPerformed

    private void radioButton_PManufaturadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioButton_PManufaturadoMouseClicked

    }//GEN-LAST:event_radioButton_PManufaturadoMouseClicked

    private void radioButton_PManufaturadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton_PManufaturadoActionPerformed

        controler.opProdutos("TIPO_MANUFATURADO");
    }//GEN-LAST:event_radioButton_PManufaturadoActionPerformed

    private void radioButton_opEstoqueSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton_opEstoqueSimActionPerformed

        controler.opProdutos("OP_EStoque_SIM");
    }//GEN-LAST:event_radioButton_opEstoqueSimActionPerformed

    private void radioButton_opEstoqueNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton_opEstoqueNaoActionPerformed

        controler.opProdutos("OP_ESTOQUE_NAO");
    }//GEN-LAST:event_radioButton_opEstoqueNaoActionPerformed

    private void txt_nomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomeProdutoActionPerformed

    private void txt_grauToxicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_grauToxicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_grauToxicoActionPerformed

    private void txt_produto_id_auxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_produto_id_auxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_produto_id_auxActionPerformed

    private void txt_fornecedor_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fornecedor_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fornecedor_idActionPerformed

    private void button_verificarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_verificarFornecedorActionPerformed

        controler.getNomeFornecedor();
    }//GEN-LAST:event_button_verificarFornecedorActionPerformed

    private void button_buscarProdutoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_buscarProdutoIDActionPerformed

        controler.buscarProdutoID();
    }//GEN-LAST:event_button_buscarProdutoIDActionPerformed

    private void button_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_atualizarActionPerformed

        controler.updateProduto();
    }//GEN-LAST:event_button_atualizarActionPerformed

    private void txt_produtoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_produtoIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_produtoIdActionPerformed

    private void button_alterarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_alterarTipoActionPerformed
        controler.opProdutos("ALTERAR_TIPO");
    }//GEN-LAST:event_button_alterarTipoActionPerformed

    private void button_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_salvarActionPerformed
        controler.salvarProduto();
    }//GEN-LAST:event_button_salvarActionPerformed

    private void button_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_excluirActionPerformed

        controler.deleteProdutoId();
    }//GEN-LAST:event_button_excluirActionPerformed

    private void button_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelarActionPerformed

        controler.apagarDados();
    }//GEN-LAST:event_button_cancelarActionPerformed

    private void button_buscarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_buscarTodosActionPerformed

        controler.getProdutos();

    }//GEN-LAST:event_button_buscarTodosActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Produtos().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.ButtonGroup buttonGroup2;
    public javax.swing.JButton button_alterarTipo;
    public javax.swing.JButton button_atualizar;
    public javax.swing.JButton button_buscarProdutoID;
    public javax.swing.JButton button_buscarTodos;
    public javax.swing.JButton button_cancelar;
    public javax.swing.JButton button_excluir;
    public javax.swing.JButton button_salvar;
    public javax.swing.JToggleButton button_verificarFornecedor;
    public javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JRadioButton radioButton_PManufaturado;
    public javax.swing.JRadioButton radioButton_insumo;
    public javax.swing.JRadioButton radioButton_opEstoqueNao;
    public javax.swing.JRadioButton radioButton_opEstoqueSim;
    public javax.swing.JTable tabela;
    public javax.swing.JTextField txt_formulaQuimica;
    public javax.swing.JTextField txt_fornecedor_id;
    public javax.swing.JTextField txt_grauToxico;
    public javax.swing.JTextField txt_nomeFornecedor;
    public javax.swing.JTextField txt_nomeProduto;
    public javax.swing.JTextField txt_produtoId;
    public javax.swing.JTextField txt_produto_id_aux;
    public javax.swing.JTextField txt_valorAtual;
    public javax.swing.JTextField txt_valorMaximo;
    public javax.swing.JTextField txt_valorMinimo;
    // End of variables declaration//GEN-END:variables
}
