/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import entidades.SistemaDeControle;
import entidades.Produto;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import persistencia.IComponenteDao;
import persistencia.IProdutoDao;
import persistenciaSql.ComponenteDao;
import persistenciaSql.ProdutoDao;

/**
 *
 * @author Rodrigo
 */
public class RegistrarProducao extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarProducao
     */
    public RegistrarProducao() {
        initComponents();
        this.loadingJComboBox(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jpanel_registrarProducao = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_quantidade = new javax.swing.JTextField();
        button_registrar = new javax.swing.JButton();
        jComboBox_NomePManufaturados = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Produção");
        setFont(new java.awt.Font("Agency FB", 0, 10)); // NOI18N
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        Jpanel_registrarProducao.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Produto:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Quantidade:");

        button_registrar.setBackground(new java.awt.Color(0, 51, 255));
        button_registrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        button_registrar.setForeground(new java.awt.Color(255, 255, 255));
        button_registrar.setText("Registrar");
        button_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_registrarActionPerformed(evt);
            }
        });

        jComboBox_NomePManufaturados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_NomePManufaturadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Jpanel_registrarProducaoLayout = new javax.swing.GroupLayout(Jpanel_registrarProducao);
        Jpanel_registrarProducao.setLayout(Jpanel_registrarProducaoLayout);
        Jpanel_registrarProducaoLayout.setHorizontalGroup(
            Jpanel_registrarProducaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_registrarProducaoLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txt_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Jpanel_registrarProducaoLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBox_NomePManufaturados, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(button_registrar)
                .addGap(86, 86, 86))
        );
        Jpanel_registrarProducaoLayout.setVerticalGroup(
            Jpanel_registrarProducaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_registrarProducaoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(Jpanel_registrarProducaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(button_registrar)
                    .addComponent(jComboBox_NomePManufaturados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Jpanel_registrarProducaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        getContentPane().add(Jpanel_registrarProducao);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loadingJComboBox(){
        IProdutoDao iProdutoDao = new ProdutoDao(); 
        List<Produto> produtos; 
        Produto p; 
        try {
           produtos = iProdutoDao.getProdutosTipo("PM"); 
           if(produtos != null){
               jComboBox_NomePManufaturados.addItem("");
               for(int iCont=0; iCont < produtos.size(); iCont++){
                   p = produtos.get(iCont); 
                   jComboBox_NomePManufaturados.addItem(p.getNome());
               }       
           }
        } catch (Exception e) {
        }
    }
    private void button_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_registrarActionPerformed
        List<Produto> produtosModificados; 
        ArrayList<Produto> produtos = null; 
        IProdutoDao iProdutoDao = new ProdutoDao(); 
        try { 
            produtos = iProdutoDao.getProdutos();
        } catch (Exception ex) {
            Logger.getLogger(RegistrarProducao.class.getName()).log(Level.SEVERE, null, ex);
        }
        SistemaDeControle controladorProdutos = new SistemaDeControle();
        controladorProdutos.setProdutos(produtos);
        if(!jComboBox_NomePManufaturados.getSelectedItem().equals("") && !txt_quantidade.getText().isEmpty()){
            String nomeProduto = (String) jComboBox_NomePManufaturados.getSelectedItem(); 
            produtosModificados = controladorProdutos.registrarProducao(nomeProduto, Float.parseFloat(txt_quantidade.getText())); 
            try {
                iProdutoDao.updateEstoqueProduto((ArrayList<Produto>) produtosModificados);
                JOptionPane.showMessageDialog(null, "Produção Atualizada Com Sucesso");
            } catch (Exception ex) {
                Logger.getLogger(RegistrarProducao.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_button_registrarActionPerformed

    private void jComboBox_NomePManufaturadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_NomePManufaturadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_NomePManufaturadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarProducao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jpanel_registrarProducao;
    private javax.swing.JButton button_registrar;
    private javax.swing.JComboBox<String> jComboBox_NomePManufaturados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txt_quantidade;
    // End of variables declaration//GEN-END:variables
}
